# Generated by Django 3.1.6 on 2021-02-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210216_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness_address',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='buisness_contact',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='buisness_reviews',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='buisness_socials',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='buisness_socials',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='buisness_address',
        ),
        migrations.DeleteModel(
            name='buisness_Contact',
        ),
        migrations.DeleteModel(
            name='Buisness_reviews',
        ),
        migrations.DeleteModel(
            name='buisness_socials',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='listing',
        ),
        migrations.DeleteModel(
            name='SocialPlatforms',
        ),
    ]
