# Generated by Django 3.1.6 on 2021-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness_reviews',
            name='photo',
            field=models.ImageField(upload_to='listing-reviews/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='icon',
            field=models.ImageField(null=True, upload_to='socials/'),
        ),
    ]
