# Generated by Django 3.1.6 on 2021-02-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210217_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companyName',
        ),
    ]
